### ISSUE TITLE
ეს რატომ გახდა საჭირო?

### ISSUE THREAD

**Issue by MariamKipshidze** [Gvantsie/book_market#3]
https://github.com/Gvantsie/book_market/blob/5dde6ef0c90da9717acb00fca14f4ad328669e81/market/models.py#L22

**Comment by Gvantsie** [comment]
ისე ვერ ვაკავშირებდი კატეგორიებს, ბევრი ვარიანტი ვცადე, ბოლოს შეიძლება სულაც არ იყო აუცილებელი მისი დატოვება.

**Comment by MariamKipshidze** [comment]
არ ჭირდება, მოგვიანებით ინდივიდუალურად შეგვიძლია გავიაროთ, თუ გადამავიწყდა შემახსენე
