### ISSUE TITLE
მოკავშირე ფილდები ( FK, M2M )  მოდელის თავში დაწერე ხოლმე რომ მარტივად მიკვლევადი იყოს და უფრო მოწესრიგებული მოდელი გქონდეს

### ISSUE THREAD

**Issue by MariamKipshidze** [Gvantsie/book_market#4]
https://github.com/Gvantsie/book_market/blob/5dde6ef0c90da9717acb00fca14f4ad328669e81/market/models.py#L36

**Comment by Gvantsie** [comment]
Categories & author გულისხმობთ? რაზეც რილეიშენშიფები მაქვს

**Comment by MariamKipshidze** [comment]
კი, მაგას ვგულისხმობ
